fellowship/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("hello", views.hello, name="hello"),
    path('teams', views.team_list, name='team_list'),
    path('teams/create', views.team_create, name='team_create'),
    path('teams/retrieve/<int:id>', views.team_retrieve, name='team_retrieve'),
    path('teams/update/<int:id>', views.team_update, name='team_update'),
    path('teams/delete/<int:id>', views.team_delete, name='team_delete'),

    path('members', views.MemberList.as_view(), name='member_list'),
    path('members/create', views.MemberCreate.as_view(), name='member_create'),
    path('members/retrieve/<int:pk>', views.MemberRetrieve.as_view(), name='member_retrieve'),
    path('members/update/<int:pk>', views.MemberUpdate.as_view(), name='member_update'),
    path('members/delete/<int:pk>', views.MemberDelete.as_view(), name='member_delete'),
]

lotr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("fellowship/", include("fellowship.urls")),

]

fellowship/models.py
from django.db import models

class TimeStampable(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Team(TimeStampable):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name




class Member(TimeStampable):
    RACES = (
        (1, "Hobbit"),
        (2, "Human"),
        (3, "Elf"),
        (4, "Dwarf"),
        (5, "Other")
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    race = models.IntegerField(choices=RACES)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

fellowship/forms.py
from django import forms
from .models import Team


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "name",
        ]

fellowship/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from fellowship.forms import TeamForm
from fellowship.models import Team, Member


def hello(request):
    return HttpResponse("Greetings, travellers.")


def team_create(request):
    template = "fellowship/team_form.html"
    context = {}

    form = TeamForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("team_list")
    context['form'] = form
    return render(request, template, context)


def team_list(request):
    template = "fellowship/team_list.html"
    context = {"teams": Team.objects.all()}
    return render(request, template, context)


def team_retrieve(request, id):
    template = "fellowship/team_detail.html"
    context = {"team": Team.objects.get(id=id)}
    return render(request, template, context)


def team_update(request, id):
    template = "fellowship/team_form.html"
    context = {}
    obj = get_object_or_404(Team, id=id)

    form = TeamForm(request.POST or None, instance = obj)
    if form.is_valid():
        form.save()
        return redirect("team_list")
    context['form'] = form
    return render(request, template, context)


def team_delete(request, id):
    template = "fellowship/team_delete.html"
    context = {}
    obj = get_object_or_404(Team, id = id)
    if request.method == "POST":
        obj.delete()
        return redirect("team_list")
    return render(request, template, context)


class MemberCreate(CreateView):
    model = Member
    fields = ['first_name', 'last_name', 'race', 'team']
    success_url = reverse_lazy('member_list')


class MemberList(ListView):
    model = Member


class MemberRetrieve(DetailView):
    model = Member


class MemberUpdate(UpdateView):
    model = Member
    fields = '__all__'
    success_url = reverse_lazy('member_list')


class MemberDelete(DeleteView):
    model = Member
    success_url = reverse_lazy('member_list')

fellowship/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Fellowship</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <header>
        <!-- Common header content -->
    </header>

    <nav>
        <!-- Common navigation content -->
    </nav>

    <main>
        <div class="container">
        {% block content %}{% endblock %}
        </div>
    </main>

    <footer>
        <!-- Common footer content -->
    </footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

fellowship/templates/fellowship/member_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Member Delete</h1>
    <form method="POST">
        {% csrf_token %}
        <p>Are you want to delete this member ?</p>
        <div class="">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-primary" href="{% url 'team_retrieve' object.team.id %}" class="badge badge-primary">Cancel</a>
        </div>
    </form>
{% endblock %}

fellowship/templates/fellowship/member_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Member Details</h1>
    <h2>Name: {{ object.first }} {{ object.last_name }}</h2>
    <h3>Race: {{ object.race }} </h3>
    <div class=""><a class="btn btn-primary" href="{% url 'team_retrieve' object.team.id %}"
                     class="badge badge-primary">Team</a></div>
{% endblock %}

fellowship/templates/fellowship/member_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Member Create/Edit</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create/Edit</button>
    </form>
{% endblock %}

fellowship/templates/fellowship/member_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Members</h1>
    <div class="">
        <ol class="list-group">
            {% for member in object_list %}
                <div class="row">
                    <div class="col">
                        <li class="list-group-item"><span></span> {{ member.last_name }} {{ member.get_race_display }}
                        </li>
                    </div>
                    <div class="col">
                        <a class="btn btn-primary" href="{% url "member_retrieve" member.id %}">View</a>
                        <a class="btn btn-warning" href="{% url "member_update" member.id %}">Edit</a>
                        <a class="btn btn-danger" href="{% url "member_delete" member.id %}">Delete</a>
                    </div>
                </div>
            {% endfor %}
        </ol>
    </div>
    <div class=""><a class="btn btn-primary" href="{% url 'member_create' %}" class="badge badge-primary">Create New
        Member</a>
        <a class="btn btn-primary" href="{% url 'team_list' %}" class="badge badge-primary">Teams</a></div>
{% endblock %}

fellowship/templates/fellowship/team_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Team Delete</h1>
    <form method="POST">
        {% csrf_token %}
        <p>Are you want to delete this team ?</p>
        <div class="">
            <button type="submit" class="btn btn-danger">Delete</button>
            <a class="btn btn-primary" href="{% url 'team_list' %}" class="badge badge-primary">Cancel</a>
        </div>
    </form>
{% endblock %}

fellowship/templates/fellowship/team_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Team Details</h1>
    <h2>Name: {{ object.name }}</h2>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Race</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for member in object.member_set.all %}
            <tr>
                <th scope="row">{{ member.id }}</th>
                <td>{{ member.first_name }}</td>
                <td>{{ member.last_name }}</td>
                <td>{{ member.get_race_display }}</td>
                <td>
                    <a class="btn btn-primary" href="{% url "member_retrieve" member.id %}">View</a>
                    <a class="btn btn-warning" href="{% url "member_update" member.id %}">Edit</a>
                    <a class="btn btn-danger" href="{% url "member_delete" member.id %}">Delete</a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <div class=""><a class="btn btn-primary" href="{% url 'member_create' %}" class="badge badge-primary">Create New
        Member</a></div>
{% endblock %}

fellowship/templates/fellowship/team_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Team Create/Edit</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create/Edit</button>
    </form>
{% endblock %}

fellowship/templates/fellowship/team_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Teams</h1>
    <ol class="list-group">
        {% for team in teams %}
            <li class="list-group-item"><a href="{% url "team_retrieve" team.id %}">{{ team.name }}</a></li>
        {% endfor %}
    </ol>
    <div class=""><a class="btn btn-primary" href="{% url 'team_create' %}" class="badge badge-primary">Create New
        Team</a></div>

{% endblock %}